# Generated by Django 5.2 on 2025-05-01 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('CGPA', models.FloatField(default=0.0)),
                ('MCGPA', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.CharField(max_length=100)),
                ('is_major_course', models.BooleanField(default=False)),
                ('semester', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.student')),
            ],
            options={
                'db_table': 'Enrollment',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('grade', models.CharField(max_length=10)),
                ('is_major_course', models.BooleanField(default=False)),
                ('attempt', models.IntegerField(default=1)),
                ('previous_grade', models.FloatField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Project.student')),
            ],
            options={
                'db_table': 'StudentCourses',
            },
        ),
    ]
