# Generated by Django 5.2 on 2025-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='section',
            field=models.CharField(default='01', max_length=10),
        ),
    ]
