# Generated by Django 5.2 on 2025-05-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_enrollment_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='Credits',
            field=models.IntegerField(default=3),
        ),
    ]
