# Generated by Django 5.2 on 2025-05-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_enrollment_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='attempt',
            field=models.IntegerField(default=0),
        ),
    ]
